songs = {"bishakto manush": "https://youtu.be/nyq9r8OYmn0?si=qQ1C0MjHNZ2UKwqz",
         "stay":"https://youtu.be/kTJczUoc26U?si=g9P44Mabm8WhfKAh",
         "agmoni gan":"https://youtu.be/MsqpjM09MrY?si=-svweMoANaOOsimI",
         "bondhu chol":"https://youtu.be/sZdmkif8CSY?si=nmoTLLtDGm4F9dGf",
        " binding lights": "https://youtu.be/fHI8X4OXluQ",
        "shape of you": "https://youtu.be/JGwWNGJdvx8",
        "someone": "https://youtu.be/hLQl3WQQoQ0",
        "levitating": "https://youtu.be/TUVcZfQe-Kw",
        "perfect": "https://youtu.be/2Vv-BfVoq4g",
        "bad guy": "https://youtu.be/DyDfgMOUjCI",
        "uptown funk": "https://youtu.be/OPf0YbXqDm0",
        "rolling": "https://youtu.be/rYEDA3JcQqw",
        "señorita": "https://youtu.be/Pkh8UtuejGw",
        "closer": "https://youtu.be/PT2_F-1esPk",
        "stay": "https://youtu.be/kTJczUoc26U",
        "hello": "https://youtu.be/YQHsXMglC9A",
        "cheap thrills": "https://youtu.be/nYh-n7EOtMA",
        "rockabye": "https://youtu.be/papuvlVeZg8",
        "love yourself": "https://youtu.be/oyEuk8j8imI",
        "believer": "https://youtu.be/7wtfhZwyrcc",
        "love me like you do": "https://youtu.be/AJtDXIazrMo",
        "baby": "https://youtu.be/kffacxfA7G4",
        "despacito": "https://youtu.be/kJQP7kiw5Fk"
}
